[package]
name = "rusper"
version = "0.1.0"
authors = ["István Bozsó <bozso.istvan@csfk.mta.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rusper"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0"
